Добавление form_10 и form_11
mikhailprivalov/l2 pull request #1039
Opened 2021-02-24 09:32 UTC by hlebuschek

1)Отказ от видов медицинских вмешательств, включенных в перечень определенных видов медицинских вмешательств, на которые граждане дают информированное добровольное согласие при выборе врача и медицинской организации для получения первичной медико-санитарной помощи
2) Информированное добровольное согласие на виды медицинских вмешательств, включённые в Перечень определённых видов медицинских вмешательств, на которые граждане дают информированное добровольное согласие при выборе врача и медицинской организации для получения первичной медико/санитарной помощи (по терапевтической стоматологии)

2021-02-24 10:25 UTC, moodpulse commented
Нужно обновлять форк, что бы дорабатывать на актуальной версии.
В последней были заменены проверки в гитхабе, поэтому это очень важно

2021-02-24 10:26 UTC, moodpulse commented
Сообщение branch is out of date не должно быть при создании pr

2021-02-24 10:27 UTC, moodpulse commented
Можно обновлять нажатием кнопки в гитхабе

2021-02-24 14:24 UTC, moodpulse commented on forms/forms101.py
> +
Это нужное?

2021-02-25 00:19 UTC, urchinpro requested changes

2021-02-25 00:19 UTC, urchinpro commented on forms/forms101.py
> +def form_11(request_data):
def form_03 - чем принципиально отличается от def form_11?

2021-02-25 12:56 UTC, hlebuschek commented on forms/forms101.py
> +def form_11(request_data):
По идеи принципиальной разницы нет, стоматологи хотят для себя отдельную форму, с этой идеей они пошли к старшей мед. сестре, а она а дальнейшем к нам. Убрал эту форму.

2021-02-25 13:22 UTC, closed without merging