Добавление form 10 и form 11
mikhailprivalov/l2 pull request #1058
Opened 2021-03-24 04:20 UTC by hlebuschek

Форма 10 является "Картой учета профилактического медицинского осмотра (диспансеризации)"
Форма 11 является " Отказом от видов медицинских вмешательств, включенных в Перечень определенных видов медицинских вмешательств, на которые граждане дают информированное добровольноe  согласие при выборе врача и медицинской организации для получения первичной медико-санитарной помощи"

2021-03-26 04:02 UTC, D00dleman reviewed
norm

2021-03-27 14:34 UTC, urchinpro commented on forms/forms101.py
> +
зачем вертикальный интервал

2021-03-27 14:34 UTC, urchinpro commented on forms/forms101.py
> +    objs.append(
может в одну строчку? и далее также по смыслу

2021-03-27 14:34 UTC, urchinpro commented on forms/forms101.py
> +    )
в одну строку лучше?

2021-03-27 14:35 UTC, urchinpro requested changes
нужны правки

2021-03-27 14:37 UTC, urchinpro commented on forms/forms101.py
> +
лишняя пустая строка

2021-03-30 13:29 UTC, urchinpro approved these changes

2021-03-30 13:29 UTC, merged