Link eln
mikhailprivalov/l2 pull request #1137
Opened 2021-05-03 10:56 UTC by urchinpro

2021-05-03 19:22 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        eln_link_made: ''
Пустые строки в виде значений по умолчанию.
Не надо использовать их так.
Если не нужно ставить правильный тип – к примеру когда в переменных числа – то надо null выбирать.

2021-05-03 19:22 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        eln_link_made: ''
Стоит веде в этом PR сделать нормальные типы

2021-05-03 19:22 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        eln_link_made: ''
И оставить пустые строки только там, где будут строки

2021-05-03 19:24 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +            window.open(myWidowEln);
Почему не _blank?

2021-05-03 19:24 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        let openWindow = null;
Почему тут везде let, а не const?

2021-05-03 19:28 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        await this.get_eln()
Этот вызов лучше закэшировать локально

2021-05-03 19:28 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        await this.get_eln()
Что бы второй раз не ходить

2021-05-03 19:29 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        await this.get_eln()
И добавить INC_LOADING

2021-05-03 19:29 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        await this.get_eln()
Ну и DEC_LOADING

2021-05-03 19:31 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +            openWindow.close()
Лучше второй вызов window.open положить внутрь сюда и обернуть в Promise. Внутри второго таймаута сделать resolve();

2021-05-03 19:31 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +            openWindow.close()
И сделать await потом. А после уже DEC_LOADING

2021-05-03 19:32 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        let myWidowEln = this.eln_link_made
Тут ещё кажется нужно проверить на заполненность данных. И выводить errmessage, если пусто

2021-05-03 19:33 UTC, moodpulse commented on l2-frontend/src/ui-cards/DoctorSchedule.vue
> +        let openWindow = null;
Тут моменты, аналогичные l2-frontend/src/pages/ResultsParaclinic.vue

2021-05-03 19:36 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +      async open_sick() {
Ниже увидел дубликат кода фактически в l2-frontend/src/ui-cards/DoctorSchedule.vue с чуть другим отображением и ссылками.
Можно назвать компонент RmisLink.
Нужно сделать просто всё внутри того компонента и по опциональному пропсу сделать, что бы было ЭЛН, а не в регистратуру.
И <li> вынести в <ul class="nav navbar-nav"> там

2021-05-03 19:39 UTC, moodpulse commented on api/views.py
> +    d = users.DoctorProfile.objects.filter(user=request.user).first()
Можно просто
```suggestion
    d = request.user.doctorprofile
```

2021-05-03 19:39 UTC, moodpulse commented on api/views.py
> +    return JsonResponse({'eln_auth': ELN_LINK_AUTH.replace('userlogin', d.rmis_login).replace('userpassword', d.rmis_password), 'eln_made': ELN_LINK_MADE,
Странно, что doc_schedule выше определён, а остальное тут.
Нужно одинаково сделать

2021-05-03 19:40 UTC, moodpulse requested changes
Нужны правки

2021-05-04 00:01 UTC, urchinpro commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +        eln_link_made: ''
+

2021-05-04 12:25 UTC, closed without merging