Download directory for field
mikhailprivalov/l2 pull request #1426
Opened 2021-10-16 07:47 UTC by urchinpro

2021-10-16 11:39 UTC, moodpulse commented
Хотелось бы описание, что это и зачем)

2021-10-16 12:19 UTC, mikhailprivalov requested changes

2021-10-16 12:19 UTC, mikhailprivalov commented on l2-frontend/src/pages/ExtraNotification.vue
> +    window.open(`/forms/json-nofication?pk=[${ids}]`);
Но ведь ids встанут как стринговый вариант массива или чего то ещё. 
Надо убрать квадратные скобки и вставить через json stringify

2021-10-17 12:01 UTC, urchinpro commented on l2-frontend/src/pages/ExtraNotification.vue
> +    window.open(`/forms/json-nofication?pk=[${ids}]`);
http://127.0.0.1:8060/directions/pdf?napr_id=[227316,227315]

здесь также

2021-10-17 12:02 UTC, urchinpro commented on l2-frontend/src/pages/ExtraNotification.vue
> +    window.open(`/forms/json-nofication?pk=[${ids}]`);
http://127.0.0.1:8060/forms/extra-nofication?pk=[227205]
аналогично

2021-10-17 14:41 UTC, mikhailprivalov commented on l2-frontend/src/pages/ExtraNotification.vue
> +    window.open(`/forms/json-nofication?pk=[${ids}]`);
Это аналогично такой строчке 
```suggestion
    window.open(`/forms/json-nofication?pk=[${ids.toString()}]`);
```

вроде бы это даёт результат, но ненадёжно.

Давай сделаем так
```suggestion
    window.open(`/forms/json-nofication?pk=${JSON.stringify(ids)}`);
```

2021-10-17 14:53 UTC, mikhailprivalov commented on l2-frontend/src/pages/ExtraNotification.vue
> +    window.open(`/forms/json-nofication?pk=[${ids}]`);
Я понял, что уже так сделано в других местах.
Но это криво, так не надо. Не знаю, как оно попало в репо, я это случайно сделал или на ревью не увидел. Но такого кода лучше не добавлять

2021-10-18 00:08 UTC, merged