Visit report
mikhailprivalov/l2 pull request #152
Opened 2019-07-14 12:49 UTC by urchinpro

2019-07-14 21:23 UTC, moodpulse commented on directions/models.py
> +from datetime import date
date тут не нужно проде

2019-07-14 21:24 UTC, moodpulse commented on lq/models.py
> +# Create your models here.
Это лучше убирать

2019-07-14 21:25 UTC, moodpulse commented on mainmenu/views.py
> +
PEP8 тут должен реагировать на лишние переносы строк

2019-07-14 21:27 UTC, moodpulse commented on statistic/templates/statistic.html
> +{#            </div>#}
Зачем комментировать это?

2019-07-14 21:27 UTC, moodpulse commented on statistic/templates/statistic.html
> +{#            </div>#}
Убрать просто лучше

2019-07-14 21:28 UTC, moodpulse commented on statistic/views.py
> +        print(type(d_s))
print ы нужно убрать

2019-07-14 21:28 UTC, moodpulse commented on statistic/views.py
> +        import datetime
Это уже импортировано сверху

2019-07-14 21:29 UTC, moodpulse commented on statistic/views.py
> +        # d_e = json.loads(data_date)
Лучше убирать код, а не комментировать. CVS для этого уже придумана

2019-07-14 21:30 UTC, moodpulse commented on statistic/views.py
> +
И тут по PEP8 не то

2019-07-14 21:32 UTC, moodpulse commented on statistic/structure_sheet.py
> +    return ws1
У этого файла тоже проблемы по PEP8. Тут "Файл не закончен символом новой строки"

2019-07-14 21:32 UTC, moodpulse commented on statistic/sql_func.py
> +
Тут многовато переносов

2019-07-14 21:35 UTC, moodpulse commented on statistic/views.py
> +                current_patient_napr = f +' ' + n + ' ' + p + '\n' + current_napr
Лучше такие вещи писать так:
`current_patient_napr = f'{f} {n} {p}\n{current_napr}'`

2019-07-14 21:37 UTC, moodpulse commented on statistic/views.py
> +                polis_n = issled[4] if issled[4] else ''
Это можно писать проще:
`polis_n = issled[4] or ''`

2019-07-14 21:39 UTC, moodpulse commented on statistic/views.py
> +                        from _collections import OrderedDict
Не стоит этого делать в цикле

2019-07-14 21:40 UTC, moodpulse commented on statistic/views.py
> +                                current_uet = temp_d.get(n[10]) if temp_d.get(n[10]) else 0
Можно попробовать так:
`current_uet = temp_d.get(n[10], 0)`

2019-07-14 21:41 UTC, moodpulse commented on statistic/views.py
> +                                total_report_dict[int(n[2])] = {n[10]:temp_uet, n[11]:temp_uet2}
Тут n[2] приводится к int, а выше нет. Есть потенциальная проблема

2019-07-14 21:42 UTC, moodpulse commented on statistic/views.py
> +                        titles_list = [tk for tk in titles_set.keys()]
Если просто `titles_set.keys()` не годится, можно сделать `list(titles_set.keys())`

2019-07-14 21:45 UTC, moodpulse commented on statistic/structure_sheet.py
> +        ws1.cell(row=3, column=2 + i).value = 1 + i
Тут к `i` добавляется `2` и `1`. Может просто `range` лучше стартовать с `1` и до `32` и прибавлять `1` и ничего?

2019-07-14 21:46 UTC, moodpulse commented on statistic/structure_sheet.py
> +            print(r)
print-ы

2019-07-14 21:46 UTC, moodpulse commented on statistic/structure_sheet.py
> +            r = titles.get(res)
`r` похоже не нужно

2019-07-14 21:47 UTC, moodpulse commented on statistic/structure_sheet.py
> +    # style_border1.alignment = Alignment(wrap_text=True, horizontal='center', vertical='center')
Закомментированный код надо убирать

2019-07-14 21:49 UTC, moodpulse commented on forms/forms_func.py
> +    # canvas.setFillColor(HexColor(0xfc5749))
коммент-код

2019-07-14 21:50 UTC, moodpulse commented on forms/forms_func.py
> +        demo_text2 = "Для лзнакомнения с функционалом      "
Опечатка `лзнакомнения`

2019-07-14 21:51 UTC, moodpulse commented on forms/forms_func.py
> +    if demo:
Может просто если не `demo` – выходить из функции?

2019-07-14 21:51 UTC, moodpulse commented on forms/forms_func.py
> +    if demo:
Тут так же лучше выход при не `demo` и тексты не заполнены похоже

2019-07-14 21:52 UTC, moodpulse commented on lq/admin.py
> +# Register your models here.
Это boilerplate-комментарии, от них лучше сразу избавляться

2019-07-14 21:56 UTC, moodpulse commented on results/views.py
> +            demo_func(canvas)
Пара моментов:
1. Лучше не называть переменные "отрицательно (not)", гораздо понятнее будет `need_demo_protect`;
2. Можно вверху функции просто выйти, если `not need_demo_protect` и дальше просто продолжить без вложенности какой либо. В случае, если demo не нужно - будет небольшой прирост производительности (не нужно save и restore)

2019-07-14 21:59 UTC, moodpulse commented on rmis_integration/client.py
> +                elif t.title == "Иностранный паспорт":
Надо это решить иначе.
В РМИС должен быть такой документ, но название, может, иное.
Варианта 2 – поменять в базе - сделать точно как в РМИС. Или найти id типа документа в РМИС и сделать как со СНИЛСом

2019-07-14 22:01 UTC, moodpulse commented on statistic/sql_func.py
> +        Select * from t_iss
Предлагаю подвести весь SQL под единый стиль:
сделать названия операторов капсом (SELECT FROM WHERE WITH AND итд), а то всё разное

2019-07-14 22:02 UTC, moodpulse commented on statistic/sql_func.py
> +                    ):
Странности форматирования, лучше тоже под PEP8 подвести эти файлы, может руками, если строки портит

2019-07-14 22:03 UTC, moodpulse commented on statistic/sql_func.py
> +        Select * from t_iss
Ревью SQL-ов тоже надо провести, так как кода куча.
Но после форматирования. И лучше всякие `t_iss` и `t_j` как то чуть понятнее назвать или хотя бы комментарий оставить что где

2019-07-14 22:05 UTC, moodpulse commented on statistic/structure_sheet.py
> +    # ws1.column_dimensions[get_column_letter(1)].width = 22
Коммент код

2019-07-14 22:05 UTC, moodpulse commented on statistic/structure_sheet.py
> +        for j in range(20):
Можно стартовать с `1` и не прибавлять единицу постоянно

2019-07-14 22:07 UTC, moodpulse commented on statistic/views.py
> +            ws1.column_dimensions[get_column_letter(col + 1)].width = 7
Вообще не совсем понятно, зачем переменная col тут. Можно же просто `2` написать

2019-07-14 22:09 UTC, mikhailprivalov requested changes
Нужны фиксы по комментам

2019-07-14 23:57 UTC, urchinpro commented on statistic/views.py
> +        import datetime
import datetime - убрал верх. 
Но делал для единообразия, т.к. в условиях: 
elif tp == "lab-staff", 
elif tp == "journal-get-material". 
Свой import datetime.

2019-07-14 23:57 UTC, urchinpro commented on statistic/views.py
> +        # d_e = json.loads(data_date)
Убрано

2019-07-15 00:20 UTC, urchinpro commented on statistic/structure_sheet.py
> +            r = titles.get(res)
r думаю нужен. 
Мы знаем в какую строку вставлять данные. Услуги уникально записаны заранее в ячейки

2019-07-17 08:46 UTC, mikhailprivalov requested changes

2019-07-17 08:46 UTC, moodpulse commented on users/models.py
> +            ("всех" if self.podrazdeleniye is None else str(self.podrazdeleniye)) if self.doc is None else str(
Можно is None не писать, так будет более кратко

2019-07-17 08:46 UTC, moodpulse commented on forms/forms_func.py
> +from reportlab.lib.units import mm
Эти три новые зависимости тут нужны? Других изменений в файле не вижу

2019-07-17 08:46 UTC, moodpulse commented on statistic/views.py
> +        ws.cell(row=1, column=(6)).style = style_o
Скобки тоже можно убрать)

2019-07-17 08:56 UTC, urchinpro commented on users/models.py
> +            ("всех" if self.podrazdeleniye is None else str(self.podrazdeleniye)) if self.doc is None else str(
Это вроде не мой код. Я даже его не читал..

2019-07-20 22:26 UTC, merged