Forms lk
mikhailprivalov/l2 pull request #1629
Opened 2022-02-21 13:52 UTC by urchinpro

2022-02-21 15:42 UTC, moodpulse requested changes

2022-02-21 15:42 UTC, moodpulse commented on integration_framework/utils.py
> +def check_type_file(file):
Выходит, что аргумент не file, а file_path

2022-02-21 15:42 UTC, moodpulse commented on integration_framework/utils.py
> +    if "pdf" in type_file.lower() or "jpeg" in type_file.lower():
Два раза lower, вообще вроде как он капсом не может быть, как я думал

2022-02-21 15:42 UTC, moodpulse commented on integration_framework/views.py
> +        if file and file.size > 3145728:
Зашит размер, лучше хотя бы коммент написать, сколько это в кб

2022-02-21 15:42 UTC, moodpulse commented on integration_framework/views.py
> +        if file and file.size > 3145728:
Или мб

2022-02-21 15:42 UTC, moodpulse commented on integration_framework/views.py
> +        if file and PlanHospitalizationFiles.objects.filter(plan=plan, uploaded_file__isnull=False).count() >= 3:
Лимит лучше в local settings

2022-02-21 15:42 UTC, moodpulse commented on integration_framework/views.py
> +        if file and PlanHospitalizationFiles.objects.filter(plan=plan, uploaded_file__isnull=False).count() >= 3:
Лимит по размеру и по количеству стоит сделать настройками и сделать апи для получения лимитов

2022-02-21 15:42 UTC, moodpulse commented on integration_framework/views.py
> +                'createdAt': strfdatetime(row_file.created_at, "%d.%m.%Y %X"),
То же самое надо ещё для л2 интерфейса

2022-02-22 02:29 UTC, urchinpro commented on integration_framework/views.py
> +        if file and file.size > 3145728:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/41939763/155052083-08839dcf-6c9f-485e-963e-b9e1cd1c24bd.png">

2022-02-22 02:30 UTC, urchinpro commented on integration_framework/views.py
> +        if file and file.size > 3145728:
надо ли? делал по подобию как в call

2022-02-22 06:38 UTC, moodpulse commented on integration_framework/views.py
> +        if file and file.size > 3145728:
Я про комментарий, сколько это

2022-02-22 06:38 UTC, moodpulse requested changes

2022-02-22 06:38 UTC, moodpulse commented on laboratory/settings.py
> +LK_FORMS = []
Что внутри должно быть? 
Оставь коммент с примером

2022-02-22 14:16 UTC, moodpulse requested changes

2022-02-22 14:16 UTC, mikhailprivalov commented on results/prepare_data.py
> +    if not napr_child and len(procedurals_diary) > 0:
Count должен быть. И ниже тоже возможно

2022-02-22 14:16 UTC, mikhailprivalov commented on results/prepare_data.py
> +    if not napr_child and len(procedurals_diary) > 0:
А не len

2022-02-22 23:51 UTC, moodpulse requested changes
апи на получение лимитов по файлам я не увидел:(

2022-02-28 09:57 UTC, merged