Files to protocol
mikhailprivalov/l2 pull request #1639
Opened 2022-03-04 14:14 UTC by urchinpro

2022-03-05 07:33 UTC, moodpulse requested changes
Нужны правки по комментариям и по моим сообщениям по поводу дизайна

2022-03-05 07:33 UTC, moodpulse commented on l2-frontend/src/modals/FileAddModal.vue
> +            fileName = '';
Method лучше добавить

2022-03-05 07:33 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +              <file-add v-if="row.research.enabled_add_files" :iss_pk="row.pk" :count_files="row.countFiles"/>
Почему компоненты в виде file-name
А не FileAdd?

2022-03-05 07:33 UTC, moodpulse commented on l2-frontend/src/ui-cards/Favorites.vue
> +                html: '#addfile-view',
Странные правки в файле favorites

2022-03-05 07:36 UTC, moodpulse requested changes

2022-03-05 07:36 UTC, moodpulse commented on api/directions/views.py
> +def add_file(request):
Почему файл загрузить может кто угодно?

2022-03-05 07:38 UTC, moodpulse requested changes

2022-03-05 07:38 UTC, moodpulse commented on l2-frontend/src/modals/FileAddModal.vue
> +        <input type="file" ref="file" style="display: none" @change="fileChange($event.target.files)"/>
А почему нельзя было сделать через честный input?

2022-03-05 07:38 UTC, moodpulse commented on l2-frontend/src/modals/FileAddModal.vue
> +      this.fileSize = Math.round((size / 1024 / 1024) * 100) / 100;
Странно такое зашивать, это же computed должно быть

2022-03-05 07:39 UTC, moodpulse requested changes

2022-03-05 07:39 UTC, moodpulse commented on l2-frontend/src/modals/FileAddModal.vue
> +  <modal
Это тоже компонент и то, что оно раньше было с маленькой буквы — косяк. Делай с большой. 
Ты же внизу импортируешь компонент Modal, а не modal

2022-03-07 11:56 UTC, urchinpro commented on l2-frontend/src/modals/FileAddModal.vue
> +      this.fileSize = Math.round((size / 1024 / 1024) * 100) / 100;
я из call брал - для единообразия

2022-03-08 13:13 UTC, merged