Fix custom research
mikhailprivalov/l2 pull request #1727
Opened 2022-04-29 04:50 UTC by urchinpro

## Описание изменений
1) Сustom-research - только "родительские услуги"
2) поиск по тексту в стационарных протоколах

2022-04-29 15:08 UTC, moodpulse requested changes

2022-04-29 15:08 UTC, moodpulse commented on l2-frontend/src/pages/Search.vue
> +      this.research = -1;
В геттерах такое делать не стоит. Для этого есть watch

2022-04-29 15:08 UTC, moodpulse commented on l2-frontend/src/pages/Search.vue
> +    window.open(`/ui/stationar#{%22pk%22:${historyNum},%22opened_list_key%22:null,%22opened_form_pk%22:null,%22every%22:false}`);
А _blank может тоже нужен?

2022-04-29 15:08 UTC, moodpulse commented on l2-frontend/src/pages/Search.vue
> +                  Текст (и/б)
Только по иб?

2022-04-30 00:25 UTC, urchinpro commented on l2-frontend/src/pages/Search.vue
> +                  Текст (и/б)
если чекбокс только по стационарным документам.  Еще одну строку-фильтр для это делать не стоит

2022-04-30 00:58 UTC, urchinpro commented on l2-frontend/src/pages/Search.vue
> +      this.research = -1;
перенес

2022-04-30 04:34 UTC, urchinpro commented on l2-frontend/src/pages/Search.vue
> +    window.open(`/ui/stationar#{%22pk%22:${historyNum},%22opened_list_key%22:null,%22opened_form_pk%22:null,%22every%22:false}`);
добавил. Но он и без него в новой вкладке открывался

2022-04-30 04:56 UTC, moodpulse commented on l2-frontend/src/pages/Search.vue
> +                  Текст (и/б)
Тогда надо бы по условию показать (иб)

2022-04-30 16:15 UTC, merged