Modify visit data
mikhailprivalov/l2 pull request #1759
Opened 2022-05-18 12:21 UTC by urchinpro

## Описание изменений

Регистрация направления вручную

2022-05-18 14:49 UTC, moodpulse requested changes

2022-05-18 14:49 UTC, moodpulse commented on api/directions/views.py
> +        visit_date = f"{visit_date}.000113 +0800"
Лучше часовой пояс из настроек взять

2022-05-19 00:15 UTC, urchinpro commented on api/directions/views.py
> +        visit_date = f"{visit_date}.000113 +0800"
пофиксил

2022-05-19 11:06 UTC, moodpulse approved these changes

2022-05-19 12:03 UTC, merged