Front control param
mikhailprivalov/l2 pull request #1806
Opened 2022-06-11 04:51 UTC by urchinpro

## Описание изменений
стр-ра данных на фронт по парам пациента

2022-06-11 19:42 UTC, moodpulse requested changes

2022-06-11 19:42 UTC, moodpulse commented on directions/models.py
> -    client = models.ForeignKey(Clients.Card, db_index=True, default=None, null=True, blank=True, help_text='Пациент', on_delete=models.CASCADE)
Это точно удалять хотим?

2022-06-11 19:42 UTC, moodpulse commented on clients/models.py
> +    date_end = models.DateField(help_text='Дата окончания контроля', default=None, blank=True, null=True)
Индексы специально убраны?

2022-06-11 19:42 UTC, moodpulse commented on api/patients/views.py
> +        pass
Оно ничего не делает

2022-06-11 23:31 UTC, urchinpro commented on directions/models.py
> -    client = models.ForeignKey(Clients.Card, db_index=True, default=None, null=True, blank=True, help_text='Пациент', on_delete=models.CASCADE)
Да! Без него все норм! Это на предыдщуем коммите зря добавил

2022-06-11 23:32 UTC, urchinpro commented on directions/models.py
> -    client = models.ForeignKey(Clients.Card, db_index=True, default=None, null=True, blank=True, help_text='Пациент', on_delete=models.CASCADE)
Еще пока нигде на проде не обновилось

2022-06-12 00:16 UTC, moodpulse approved these changes

2022-06-12 13:24 UTC, merged