Fix dev
mikhailprivalov/l2 pull request #182
Opened 2019-08-22 12:39 UTC by urchinpro

вот мой dev как у меня

2019-08-24 23:07 UTC, mikhailprivalov requested changes

2019-08-24 23:07 UTC, moodpulse commented on clients/admin.py
> +# class IndividualAdmin(admin.ModelAdmin):
Это надо убрать

2019-08-24 23:07 UTC, moodpulse commented on integration_framework/urls.py
> +    path('result/pdf', views.document_result),
Это тоже убрать

2019-08-24 23:07 UTC, moodpulse commented on users/management/commands/medicament_import.py
> +                KeyValue.objects.create(key='mnn', value=cells[mnn].strip())
Может сюда стоит сделать проверку на существование? Или чистку по ключам mnn всех записей при импорте, что даже логичнее

2019-08-24 23:07 UTC, moodpulse commented on yarn.lock
> +# yarn lockfile v1
Это тоже не нужно

2019-08-25 04:15 UTC, urchinpro commented on users/management/commands/medicament_import.py
> +                KeyValue.objects.create(key='mnn', value=cells[mnn].strip())
Это и удаляет все при старте:
KeyValue.objects.filter(key='mnn').delete()

2019-08-25 13:47 UTC, mikhailprivalov requested changes

2019-08-25 13:47 UTC, moodpulse commented on integration_framework/views.py
> +import simplejson as json
Это лишнее похоже

2019-08-25 13:47 UTC, moodpulse commented on l2-frontend/yarn.lock
> -# yarn lockfile v1
А это автоматом убралось? Потому что такая строка была не нужна в корне проекта, а не тут

2019-08-25 13:47 UTC, moodpulse commented on yarn.lock
> +# yarn lockfile v1
Убрать надо все же, в корне не должно быть этого

2019-08-25 14:07 UTC, moodpulse commented on users/management/commands/medicament_import.py
> +                KeyValue.objects.create(key='mnn', value=cells[mnn].strip())
Просто странно, что это завязано на заголовок.
Почему просто не удалить сверху?

2019-08-25 14:09 UTC, closed without merging