Laboratory control param
mikhailprivalov/l2 pull request #1862
Opened 2022-07-12 07:39 UTC by urchinpro

## Описание изменений
Laboratory Control param. Fix загурзить шаблон

2022-07-12 19:57 UTC, mikhailprivalov requested changes

2022-07-12 19:57 UTC, mikhailprivalov commented on l2-frontend/src/pages/Stationar/index.vue
> +      width: calc(100% - 530px);
Тут что то странное попало. Лучше описать причину, что это и зачем

2022-07-12 23:37 UTC, urchinpro commented on l2-frontend/src/pages/Stationar/index.vue
> +      width: calc(100% - 530px);
убрал-поправил

2022-07-13 06:41 UTC, moodpulse approved these changes

2022-07-13 07:12 UTC, merged