fix 500 TubeRegistration
mikhailprivalov/l2 pull request #1890
Opened 2022-07-27 14:09 UTC by urchinpro

## Описание изменений
fix-ы TubeRegistration, DocConfirm

2022-07-27 14:25 UTC, moodpulse requested changes

2022-07-27 14:25 UTC, moodpulse commented on integration_framework/views.py
> +    except:
Зачем это?

2022-07-27 14:43 UTC, urchinpro commented on integration_framework/views.py
> +    except:
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/41939763/181276797-fd83ff53-5fc6-4b96-ad41-6b3fbd482c88.png">

2022-07-27 14:43 UTC, urchinpro commented on integration_framework/views.py
> +    except:
в 500 падает

2022-07-27 17:28 UTC, moodpulse commented on integration_framework/views.py
> +    except:
Тут не происходит конвертации в json.

2022-07-27 17:28 UTC, moodpulse commented on integration_framework/views.py
> +    except:
Это только создание queryset

2022-07-27 17:29 UTC, moodpulse commented on integration_framework/views.py
> +    except:
Нужно найти место, где пробирка пытается попасть в json и сделать, что бы там была строка или число, а не объект модели

2022-07-27 23:59 UTC, urchinpro commented on integration_framework/views.py
> +    except:
<img width="809" alt="image" src="https://user-images.githubusercontent.com/41939763/181392292-9af49f38-6280-40b7-9255-5c22572af114.png">

2022-07-27 23:59 UTC, urchinpro commented on integration_framework/views.py
> +    except:
везде даты у тебя

2022-07-28 07:42 UTC, urchinpro commented on integration_framework/views.py
> +    except:
я пока убрал просто try

2022-07-28 10:15 UTC, merged