If sql
mikhailprivalov/l2 pull request #194
Opened 2019-09-01 14:00 UTC by urchinpro

2019-09-01 14:03 UTC, moodpulse commented on integration_framework/views.py
> +    d_start = f'{after_date}+08'
+08 не надо писать так, у нас не одна зона возможна

2019-09-01 14:03 UTC, moodpulse commented on integration_framework/views.py
> +    dirs = sql_if.direction_collect(d_start, type_researches, next_n)
Можно было один раз написать dirs =

2019-09-01 14:05 UTC, moodpulse commented on rmis_integration/client.py
> +        self.session = Session.proxies = {'http': '192.168.0.7:3128','https': '192.168.0.7:3128'}
Не надо это тут зашивать, тем более в старом варианте Session() создавалось, а тут другое совсем

2019-09-01 14:06 UTC, moodpulse commented on integration_framework/views.py
> +from laboratory.local_settings import AFTER_DATE
Этого AFTER_DATE по умолчанию вообще нет в settings, так не должно быть

2019-09-01 14:11 UTC, moodpulse commented on integration_framework/admin.py
> +admin.site.register(models.IntegrationResearches, ResIntertationResearches)
В этом и где то ниже файлы без переноса строки в конце, по PEP8 это требуется

2019-09-02 00:26 UTC, urchinpro commented on integration_framework/views.py
> +    d_start = f'{after_date}+08'
пофиксил

2019-09-02 00:26 UTC, urchinpro commented on integration_framework/views.py
> +    dirs = sql_if.direction_collect(d_start, type_researches, next_n)
пофиксил

2019-09-02 00:26 UTC, urchinpro commented on rmis_integration/client.py
> +        self.session = Session.proxies = {'http': '192.168.0.7:3128','https': '192.168.0.7:3128'}
пофиксил

2019-09-02 00:31 UTC, urchinpro commented on integration_framework/views.py
> +from laboratory.local_settings import AFTER_DATE
добавил

2019-09-02 00:32 UTC, urchinpro commented on integration_framework/admin.py
> +admin.site.register(models.IntegrationResearches, ResIntertationResearches)
добавил

2019-09-02 08:17 UTC, mikhailprivalov requested changes

2019-09-02 08:17 UTC, moodpulse commented on rmis_integration/client.py
> -        self.session = Session()
Надо полностью вернуть

2019-09-02 18:27 UTC, merged