Конструктор прайсов + печатные формы
mikhailprivalov/l2 pull request #1967
Opened 2022-09-10 13:15 UTC by Wellheor1

## Описание изменений
* Конструктор прайсов
* Новые печатные формы
* Правка печатных форм

2022-09-10 14:49 UTC, moodpulse requested changes

2022-09-10 14:49 UTC, moodpulse commented on api/views.py
> +def update_coast_research_in_price(request):
Цены может обновлять хоть кто?

2022-09-10 14:49 UTC, moodpulse commented on api/views.py
> +def update_coast_research_in_price(request):
Нет запретов по группам пользвателей

2022-09-10 14:49 UTC, moodpulse commented on api/views.py
> +import directory
Почему импортируем весь directory, а не то что надо? К примеру конкретные модели.

2022-09-10 14:49 UTC, moodpulse commented on api/views.py
> +                res_list["Консультации"].get(research.site_type.title).append({"id": research.pk, "label": research.title})
Почему тут и ниже сделано через get? 
Это в любом случае не сработает, потому что если ключа нет, то у None нету метода append.
Поэтому если ключи гарантируются, то надо сделать просто через []

2022-09-10 14:49 UTC, moodpulse commented on api/views.py
> +            pass
Лишнее

2022-09-10 14:49 UTC, moodpulse commented on api/views.py
> +            result_list[counter]["children"].append({"id": f'а{count}', "label": k, "children": v})
Зачем усложнять код через counter, если можно просто сначала собрать список, а потом уже append значения в result list?

2022-09-10 14:49 UTC, moodpulse commented on forms/forms105.py
> +        Paragraph(f'Подпись заведующего отделением({manager_depart}) ____________________________', style),
Перед скобкой нет пробела

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +        style="padding-left: 1%"
Паддинг в процентах — странный. Если нужен паддинг, то нужно в таких случаях абсолютное значение в пикселях

2022-09-10 14:49 UTC, moodpulse commented on forms/forms101.py
> +def form_101(request_data):
Форма точно должна быть переименована?

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      @input="getCurrentCoastResearchesInPrice(); disabled_status()"
Такое обычно делают через watch на selectedPrice

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +          :key="idx"
Key как индекс элемента нужно применять только в самых крайних случаях. Лучше выбрать что то уникальное из перебираемых объектов. К примеру id.

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      coast: null,
Пустое значение как null для текстового поля — не самое лучшее решение.

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      this.disabled = this.selectedPrice.status === false;
А почему нельзя disabled сделать через computed?

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +<script>
lang="ts" стоит использовать для всех новых компонентов.

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +        const research = CoastResearch.research.title.toString().toLowerCase();
toString тут точно нужно?

2022-09-10 14:49 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +  margin: 10px 8%;
Margin в процентах таких маленьких значений выглядит как костыль. 
Лучше пиксели, если не нужна относительность от ширины или высоты контейнера в размерах. А тут она точно не нужна.

2022-09-10 14:49 UTC, moodpulse commented on api/views.py
> +    coast_research = [{"id": data.pk, "research": {"title": data.research.title, "id": data.research.pk}, "coast": data.coast.__float__()} for data in coast_researches_data]
Конвертацией coast во float мы рискуем потерять точность, так как это преобразуется в число json и потом попадёт в js.
Лучше обойтись строкой.

2022-09-10 16:00 UTC, Wellheor1 commented on forms/forms101.py
> +def form_101(request_data):
Да, это старый вариант печатной формы, вместо него новую подсунул - @urchinpro сказал так сделать)

2022-09-18 21:29 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      this.disabled = this.selectedPrice.status === false;
почему просто не написать computed свойство?

2022-09-18 21:31 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      const { ok, message } = await this.$api('/update-coast-research-in-price', {
На обновления лучше запускать прелоадер через
await this.$store.dispatch(actions.INC_LOADING);
и убирать через
await this.$store.dispatch(actions.DEC_LOADING);

Это относится и к функции ниже.
Иначе пользователь может послать запрос два раза. Случайно или специально.

2022-09-18 21:32 UTC, moodpulse requested changes
Пара вопросов осталась

2022-09-18 21:33 UTC, moodpulse commented
И ветку обнови по develop. В гитхабе как раз кнопка update branch есть. Главное потом локально pull сделать, если изменения вносить.

Лучше сначала обновить, далее pull у себя, а потом править код

2022-09-19 06:07 UTC, Wellheor1 commented
disabled - сделал проще, статус уже приходит с сервера

2022-09-20 00:00 UTC, moodpulse requested changes
Последний вопрос остался

2022-09-20 00:00 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      return this.originalCoastResearch.filter(CoastResearch => {
CamelCase в аргументах должен быть camelCase (с нижнего регистра). 
В линтере в правилах не зафиксировано, но зафиксирую потом.

2022-09-20 14:20 UTC, moodpulse approved these changes

2022-09-20 14:37 UTC, merged