Fix construct price
mikhailprivalov/l2 pull request #1995
Opened 2022-09-26 02:46 UTC by Wellheor1

## Описание изменений
* Поправил функцию get_research_list
* Поправил фронтенд

2022-09-26 20:30 UTC, moodpulse commented on api/views.py
> +    elif float(request_data["coast"]) < 1:
То есть 0.5 р невалидно?)
Надо сделать или <= 0
или даже меньше 0
Надо с @urchinpro решить, нужно ли дать возможность обнулять цены

2022-09-26 20:38 UTC, moodpulse commented on api/views.py
> +        return JsonResponse({"ok": False, "message": "Не верная цена"})
Правильнее было бы
```suggestion
        return JsonResponse({"ok": False, "message": "Неверная цена"})
```

2022-09-26 20:39 UTC, moodpulse commented on api/views.py
>          return JsonResponse({"ok": False, "message": "Прайс не активен"})
Тут, кстати тоже
```suggestion
        return JsonResponse({"ok": False, "message": "Прайс неактивен"})
```

2022-09-26 20:39 UTC, moodpulse requested changes
Есть вопросы

2022-09-27 01:03 UTC, urchinpro commented on api/views.py
>              else:
на строке 2380, 2394 убрать continue
строку 2392 if заменить на elif

2022-09-27 01:03 UTC, urchinpro commented on api/views.py
>              else:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/41939763/192407507-a568758c-805c-4ea3-9744-19176962508b.png">


Вот кусок кода

2022-09-27 01:04 UTC, urchinpro commented on api/views.py
>              else:
continue не нужны в нужных местах поставить elif и else

2022-09-27 01:34 UTC, urchinpro commented on api/views.py
> +    elif float(request_data["coast"]) < 1:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/41939763/192410714-501f3949-9340-4022-96fb-1c81ce520f41.png">

2022-09-27 01:34 UTC, urchinpro commented on api/views.py
> +    elif float(request_data["coast"]) < 1:
плюс логи добавить в следующем обновлении

2022-09-28 04:50 UTC, urchinpro approved these changes

2022-09-28 04:53 UTC, merged