Fix coast
mikhailprivalov/l2 pull request #20
Opened 2019-03-26 07:26 UTC by urchinpro

2019-03-28 19:01 UTC, mikhailprivalov requested changes
Вижу работа ещё идет, откомментировал для исправления до слияния

2019-03-28 19:01 UTC, mikhailprivalov commented on directions/models.py
> +                    # research_coast = forms_func.get_coast(research.id, price_obj)
Такие комменты надо убирать, как и  # начало

2019-03-28 19:01 UTC, mikhailprivalov commented on clients/models.py
> +        return "{}".format(self.base.short_title)
можно просто return self.base.short_title
выше так же

2019-03-28 19:01 UTC, mikhailprivalov commented on directions/models.py
> +    def set_of_name(dir: object, doc_current: object, ofname_id: object, ofname: object) -> object:
DoctorProfile надо вернуть. object ни о чем не говорит.
в dir можно добавить Napravleniya, doc_current добавить DoctorProfile. ofname_id - похоже, что int
То есть тут надо сделать типы аргументов корректные

2019-03-28 19:01 UTC, mikhailprivalov commented on directions/models.py
> +                print(finsource.title)
Надо убрать все новые print

2019-03-28 19:01 UTC, mikhailprivalov commented on forms/forms101.py
> +                            title="Форма {}".format("Сгласие на вич"))
Сгласие

2019-03-28 19:01 UTC, mikhailprivalov commented on laboratory/settings.py
> +DEBUG = True
Обратно надо
Для этого local settings

2019-03-28 19:01 UTC, mikhailprivalov commented on forms/forms_func.py
> +    if type(dir_research_loc)==dict:
Надо автоформатированием пройтись
PEP8 лучше соблюдать

2019-03-28 19:01 UTC, moodpulse commented on forms/forms_func.py
> +                  Issledovaniya.objects.filter(napravleniye=k, research__in=v).values_list('research_id','coast','discount','how_many') if s!=None})
Можно было сделать просто выборку filter(..., coast__isnull=False)

2019-03-29 00:15 UTC, urchinpro commented on directions/models.py
> +    def set_of_name(dir: object, doc_current: object, ofname_id: object, ofname: object) -> object:
это же не мои правки DoctorProfile??

2019-03-29 18:05 UTC, merged