Параметры направления на стандартных направлениях
mikhailprivalov/l2 pull request #2148
Opened 2022-10-15 04:02 UTC by Wellheor1

## Описание изменений
* Параметры направления - на печатную форму

2022-10-15 11:11 UTC, moodpulse requested changes

2022-10-15 11:11 UTC, moodpulse commented on directions/views.py
> +        n += 1
Почему n добавляем то?)

2022-10-15 11:11 UTC, moodpulse commented on directions/views.py
> +        n += 1
И приложи, пожалуйста, как оно выглядит скриншотом

2022-10-15 11:48 UTC, Wellheor1 commented on directions/views.py
> +        n += 1
![image](https://user-images.githubusercontent.com/72241044/195984789-c6448048-85f4-4af1-ac90-1c7af67cea2c.png)

2022-10-15 13:12 UTC, urchinpro commented on directions/views.py
> +        n += 1
n * 10 здесь мало уместно. Вероятность, что будет n == 1 стремится к 100%

2022-10-15 13:20 UTC, urchinpro commented on directions/views.py
> +        n += 1
<img width="769" alt="image" src="https://user-images.githubusercontent.com/41939763/195988581-199d261c-7482-461c-9fef-eb425a89db52.png">

2022-10-15 13:20 UTC, urchinpro commented on directions/views.py
> +        n += 1
надо бы в табл обернуть иначе если длинный текст за границу вылезет

2022-10-17 02:37 UTC, Wellheor1 commented
![image](https://user-images.githubusercontent.com/72241044/196077262-cd16328e-74f8-41fc-bf16-391ebdfd08d9.png)

2022-10-17 12:44 UTC, urchinpro commented on directions/views.py
> +    for params in direction_params:
если len(direction_params)== 0 зачем цикл?

2022-10-17 12:44 UTC, urchinpro commented on directions/views.py
> +        params_data = []
Это можно выше сразу инициализировать

2022-10-17 12:45 UTC, urchinpro commented on directions/views.py
> +        params_data = [['']]
выше params_data = [] а здесь тогда append

2022-10-17 12:48 UTC, urchinpro commented on directions/views.py
> +    for params in direction_params:
а вообще лучше params_data = [ [
                Paragraph(
                    '<font face=\"OpenSansBold\" size=\"'
                    + str(font_size * 0.8)
                    + f'\">{params.title}:</font>'
                    + '<font face=\"OpenSans\" size=\"'
                    + str(font_size * 0.8)
                    + f'\"> {params.value}</font>',
                    styleSheet["BodyText"],
                )
            ]  for params in direction_params]
            
            
         если len direction_param > 0

2022-10-18 13:33 UTC, moodpulse requested changes

2022-10-18 13:33 UTC, moodpulse commented on directions/views.py
> +    params_table = Table(data=params_data, colWidths=params_col)
А зачем мы пытаемся создавать таблицу, если даже нет записей для нее?

2022-10-18 13:38 UTC, mikhailprivalov requested changes

2022-10-18 13:38 UTC, moodpulse commented on directions/views.py
> +    direction_params = DirectionParamsResult.objects.filter(napravleniye=dir)
Давай не делать тут запрос. 
Выше есть prefetch_related, нужно добавить туда, а тут забирать из dir

2022-10-20 00:18 UTC, moodpulse commented on directions/views.py
> +                    + f'\"> {params.value}</font>',
Лучше использовать string_value_normalized

2022-10-20 11:01 UTC, moodpulse approved these changes

2022-10-20 11:20 UTC, merged