Конструктор компаний
mikhailprivalov/l2 pull request #2192
Opened 2022-10-24 11:26 UTC by Wellheor1

## Описание изменений
* Добавление/редактирование компаний

2022-10-24 19:48 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +<template>
Давай форму на Formulate переделаем
Тут оно лучше подойдет
Пример в ConstructOrg

2022-10-24 19:52 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +          @input="getOnlyNumber($event, 'editCompanyInn')"
Это можно было решить через модификатор .number на v-model
С точки зрения использования Formulate будет не так актуально, там https://vueformulate.com/guide/inputs/types/text/#number
Там будет важным пункт про inputmode="numeric"

2022-10-24 19:53 UTC, moodpulse reviewed
Нужно ещё добавить валидацию клиентскую и серверную, что нужные поля заполнены

2022-10-24 19:54 UTC, moodpulse reviewed
Так же стоит добавить validation="required:trim" на поля FormulateInput

2022-10-24 19:56 UTC, moodpulse commented on api/views.py
> +    company_data = sorted(company_data, key=lambda company: company["title"])
Можно было через order_by в запросе

2022-10-24 19:56 UTC, moodpulse commented on api/views.py
> +    contract_data = sorted(contract_data, key=lambda contract: contract["label"])
Тут тоже order_by

2022-10-24 19:57 UTC, moodpulse commented on api/views.py
> +        "contract_id": current_company.contract.pk,
Лучше будет
```suggestion
        "contract_id": current_company.contract_id,
```

Иначе:
1. Это дополнительный запрос в базу
2. Если contract пуст, то должна быть ошибка

2022-10-24 19:59 UTC, moodpulse commented on api/views.py
> +            {"old_company_data": old_company_data, "new_company_data": new_company_data},
для old_company_data и new_company_data можно добавить функцию as_json в модель Company, что бы четыре раза не делать одно и то же (по всему новому коду)

2022-10-24 20:00 UTC, moodpulse commented on api/views.py
> +            130002,
Так как body в логах на создание и редактирование разные - лучше сделать разные события добавления и обновления

2022-10-24 20:01 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +      this.currentCompany = await this.$api('get-current-company', { id: company.id });
Можно так
```suggestion
      this.currentCompany = await this.$api('get-current-company', company, 'id');
```

2022-10-24 20:02 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +      this.currentCompany = await this.$api('get-current-company', { id: company.id });
api имеет такие варианты применения:
this.$api('get-current-company', { id: company.id })
this.$api('get-current-company', company, 'id');
this.$api('get-current-company', company, ['id', 'id2']);
this.$api('get-current-company', company, 'id', {moreData: 1});
this.$api('get-current-company', company, ['id', 'id2'], {moreData: 1});

2022-10-24 20:03 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +        v-model="search"
Такие поля лучше очищать от ненужных пробелов
```suggestion
        v-model.trim="search"
```

2022-10-24 20:04 UTC, moodpulse commented on api/views.py
> +        "contract_id": current_company.contract.pk,
2 - важно, потому что поле contract в компании null=True

2022-10-24 20:07 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +      } else if (this.editCompanyId === -1 && this.dataCompanyList.find((company) => company.title === this.editCompanyTitle)) {
Условие не полноценное.
Если мы меняем компанию и делаем название уже существующее, то будут дубликаты.
Плюс дубликацию проверять можно ещё по ИНН

2022-10-24 20:07 UTC, moodpulse requested changes
Есть вопросы

2022-10-25 05:16 UTC, moodpulse commented on api/urls.py
> +    path('get-current-company', views.get_current_company),
Почему get current, а не просто get?

2022-10-28 01:34 UTC, moodpulse requested changes
Есть вопросы. И прикрепи плиз скриншот результата

2022-10-28 01:34 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +        style="margin-top: 36px; padding-left: 0.75rem;"
Почему паддинги в rem?

2022-10-28 01:34 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +          <Treeselect
А если всё же formulate select?

2022-10-28 01:34 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +      this.editorCompany = this.dataCurrentCompany;
Что тут происходит?) 
Зачем столько перекладываний туда сюда и полей в data?)

2022-10-28 01:34 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +  padding-left: 0.75rem;
Не надо rem
Используй пиксели всегда, когда это возможно.

2022-10-28 01:34 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +label {
Что за стиль и для чего? 
Не стоит такие общие селекторы писать
Нужно давать классы

2022-10-28 01:34 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +        {{ editorCompany.pk ? 'Обновить компанию' : 'Добавить компанию' }}
Добавь такое computed свойство
isNewCompany, которое внутри себя будет проверять на pk.
В разметке код будет лучше.

2022-10-28 01:40 UTC, mikhailprivalov commented on l2-frontend/src/construct/ConstructCompany.vue
> +      <h6 class="text-center">
Почему это всегда отображаем?

2022-10-28 01:40 UTC, mikhailprivalov commented on l2-frontend/src/construct/ConstructCompany.vue
> +      <h6 class="text-center">
Надо на обновлении только

2022-10-28 01:40 UTC, mikhailprivalov commented on l2-frontend/src/construct/ConstructCompany.vue
> +          this.clearEditCompany();
Думаю это лучше вызвать до получения списка. У тебя там await, выходит форма очистится с лагом

2022-10-29 02:24 UTC, urchinpro commented on api/views.py
> +        company_data.ogrn = request_data["ogrn"]
orgn - заменить на ogrn

2022-10-29 02:24 UTC, urchinpro commented on api/views.py
> +        company_data.ogrn = request_data["ogrn"]
везде

2022-11-01 23:50 UTC, Wellheor1 commented
![image](https://user-images.githubusercontent.com/72241044/199363066-864d6863-37fd-4d5c-9422-dc66949c0f2f.png)
![image](https://user-images.githubusercontent.com/72241044/199363102-e9ea8adf-c9bb-475c-835e-365a321a6121.png)

2022-11-02 11:20 UTC, merged