Holter
mikhailprivalov/l2 pull request #222
Opened 2019-10-19 13:08 UTC by urchinpro

2019-10-19 14:07 UTC, mikhailprivalov requested changes

2019-10-19 14:07 UTC, mikhailprivalov commented on directions/models.py
> +
Мелочь: Кажется есть лишний перенос строки

2019-10-19 14:07 UTC, mikhailprivalov commented on integration_framework/models.py
> +    key = models.CharField(max_length=255, default="", blank=True, help_text='Приложение/объект', db_index=True)
Если это ключ, то нужно ли ему 255 длину?

2019-10-19 14:07 UTC, mikhailprivalov commented on laboratory/settings.py
> +ALLOWED_HOSTS = ['lis.fc-ismu.local', 'lis', '127.0.0.1', 'localhost', 'testserver', '192.168.0.130','192.168.10.155']
Это лучше в local settings делать, тут исторические только данные остались

2019-10-19 14:07 UTC, mikhailprivalov commented on results/views.py
> +    if len(pk) == 1 and len(link_result)==0:
Форматирование тут не правильное

2019-10-19 14:07 UTC, mikhailprivalov commented on rmis_integration/models.py
> +    holter_protocol = models.DateField(null=True, blank=True, db_index=True, help_text='Последний обработанный протокол')
Не хватает переноса строки в конце

2019-10-19 14:07 UTC, mikhailprivalov commented on rmis_integration/models.py
> +class holter_date(models.Model):
Название модели должно быть в виде НазваниеМодели

2019-10-19 14:07 UTC, mikhailprivalov commented on rmis_integration/models.py
>  # Create your models here.
Эти комменты лучше убирать, когда модели появляются

2019-10-19 14:07 UTC, mikhailprivalov commented on results/views.py
> +        pdf_all = BytesIO()
Два раза это в этом файле в этом участке кода происходит, ниже в строке 1383

2019-10-19 14:08 UTC, moodpulse commented on results/views.py
>      # cl = Client()
Коммент-код за одно лучше убрать

2019-10-19 14:09 UTC, moodpulse commented on results/views.py
> +    ################################################
Это я думаю тоже уже не надо

2019-10-19 14:09 UTC, moodpulse commented on results/views.py
> +    from pdfrw import PdfReader, PdfWriter
Лучше глобальный импорт сделать

2019-10-19 14:10 UTC, moodpulse commented on results/views.py
> +        link_files = False
Эта переменная не нужна.
Ниже напишу

2019-10-19 14:10 UTC, moodpulse commented on results/views.py
> +        if link_files:
Можно проверить по не пустому link_result

2019-10-19 14:11 UTC, moodpulse commented on results/views.py
> +    if len(pk) == 1 and len(link_result)==0:
Можно упростить так же условие: пустой список в python эквивалентен False, то есть ...and not link_result:

2019-10-19 14:11 UTC, moodpulse commented on results/views.py
> +        from pdfrw import PdfReader, PdfWriter
Это уже импортировано

2019-10-19 14:12 UTC, moodpulse commented on results/views.py
> +        date_now_str = str(random.random())+ str(date_now1)
Форматирование тут то же не то

2019-10-19 14:12 UTC, moodpulse commented on results/views.py
> +        date_now1 = datetime.datetime.strftime(datetime.datetime.now(), "%y%m%d%H%M%S%f")[:-3]
Вместо [:-3] можно убрать %f в шаблоне строки

2019-10-19 14:14 UTC, moodpulse commented on results/views.py
> +        date_now1 = datetime.datetime.strftime(datetime.datetime.now(), "%y%m%d%H%M%S%f")[:-3]
Просто учитывая рандом ниже похоже микросекунды не нужны

2019-10-19 14:15 UTC, moodpulse commented on users/management/commands/holter.py
> +        date_time = '2019-09-01 10:48:07.558120'
Лучше вынести в параметры может?

2019-10-19 14:15 UTC, moodpulse commented on users/management/commands/holter.py
> +        podrazdeleniye_pk = 85
Это в параметры надо

2019-10-19 14:16 UTC, moodpulse commented on users/management/commands/holter.py
> +            temp_dict = {k[0] : i[0]}
Тут тоже форматирование надо поправить

2019-10-19 14:17 UTC, moodpulse commented on users/management/commands/holter.py
> +                            obj_iss.link_file = today_dir + f'/{num_dir + "_" + list_fio[2]}.pdf'
Мелочь:
форматированные строки могут и лучше))
f'{today_dir}/{num_dir}_{list_fio[2]}.pdf'

2019-10-19 14:18 UTC, moodpulse commented on users/management/commands/holter.py
> +        back_days = 5
Тоже лучше в параметры

2019-10-19 14:19 UTC, moodpulse commented on users/management/commands/holter.py
> +                                exit = False
exit - зарезервированное слово, лучше другое

2019-10-20 03:15 UTC, urchinpro commented on results/views.py
> +        if link_files:
Нельзя будет. Т.к. выше главный цикл "for direction in sorted(Napravleniya.objects........."
Если Направления вперемешку, то на первом этапе мы запишем в link_result и он всегда будет не пустой

2019-10-20 09:48 UTC, moodpulse commented on users/management/commands/holter.py
> +                            obj_iss.link_file = f'{today_dir}/{num_dir}_{list_fio[2]}.pdf'
Теперь это ок, но то же самое делается в переменную link, лучше тогда в ней так сделать, а тут вообще ее использовать

2019-10-20 16:56 UTC, merged