Согласие на проведение МРТ
mikhailprivalov/l2 pull request #2293
Opened 2022-11-26 10:20 UTC by Wellheor1

## Описание изменений
*  Печатная форма согласия на проведение МРТ

2022-11-28 05:17 UTC, urchinpro approved these changes

2022-11-29 04:48 UTC, moodpulse requested changes

2022-11-29 04:48 UTC, moodpulse commented on l2-frontend/src/forms.js
> +      { url: '/forms/pdf?type=101.19&card_pk={card}', title: 'Отказ от видов медицинских вмешательств', type: '101.19' },
Почему 2 формы с одинаковым названием?

2022-11-29 04:48 UTC, moodpulse commented on l2-frontend/src/forms.js
>      title: 'Согласия',
Тут не вижу, что бы новые формы были доьавлены

2022-11-29 04:50 UTC, Wellheor1 commented on l2-frontend/src/forms.js
> +      { url: '/forms/pdf?type=101.19&card_pk={card}', title: 'Отказ от видов медицинских вмешательств', type: '101.19' },
По содержанию разные, @urchinpro сказал в local_settings DISABLED_FORM отключать будет

2022-11-29 13:54 UTC, mikhailprivalov commented on l2-frontend/src/forms.js
> +      { url: '/forms/pdf?type=101.19&card_pk={card}', title: 'Отказ от видов медицинских вмешательств', type: '101.19' },
Может хотя бы в конец добавим (101.11) и (101.19)?

2022-11-30 05:15 UTC, moodpulse commented on l2-frontend/src/forms.js
> +      { url: '/forms/pdf?type=101.11&card_pk={card}', title: 'Отказ от видов мед. вмешательств(101.11)', type: '101.11' },
```suggestion
      { url: '/forms/pdf?type=101.11&card_pk={card}', title: 'Отказ от видов мед. вмешательств (101.11)', type: '101.11' },
```

2022-11-30 05:15 UTC, moodpulse commented on l2-frontend/src/forms.js
> +      { url: '/forms/pdf?type=101.19&card_pk={card}', title: 'Отказ от видов мед. вмешательств(101.19)', type: '101.19' },
```suggestion
      { url: '/forms/pdf?type=101.19&card_pk={card}', title: 'Отказ от видов мед. вмешательств (101.19)', type: '101.19' },
```

2022-11-30 05:15 UTC, merged