Конструктор контролируемых параметров пациентов
mikhailprivalov/l2 pull request #2361
Opened 2022-12-15 01:12 UTC by Wellheor1

## Описание изменений
* Создание/редактирование контролируемых параметров пациентов
![image](https://user-images.githubusercontent.com/72241044/207748764-71483133-dbd4-4327-b33e-100385df6e5f.png)

2022-12-15 08:37 UTC, moodpulse requested changes
Нужно поправить валидатор значения. 
И предлагаю рассмотреть сортировку записей по приоритету, что бы он был более наглядный.

2022-12-15 08:37 UTC, moodpulse commented on l2-frontend/src/construct/ConstructControlParam.vue
> +    toCodeFormat(index, event, param) {
Так не надо делать) 
Тут во первых непонятно, какие данные могут поменяться. И нет гарантии, что реактивное связывание через v model не отработает после этой проверки, а не до, что в итоге окажется багом, то есть этот фикс не отработает. 
Правильно будет вынести инпут в компонент и там через watch проверять. 
Не понадобятся костыли с index, реактивность будет работать точно нормально. Ну и код будет правильный с точки зрения vue.

2022-12-15 11:36 UTC, urchinpro approved these changes

2023-01-18 02:43 UTC, Wellheor1 commented
![image](https://user-images.githubusercontent.com/72241044/213069130-abe5add8-9f4c-4f12-8f5f-9974b691951b.png)
Новая версия

2023-01-19 13:55 UTC, merged