Наборы исследований
mikhailprivalov/l2 pull request #2408
Opened 2023-01-04 05:03 UTC by Wellheor1

## Описание изменений
* Наборы исследований/услуг для отчёта
* Конструктор наборов исследований - содержание, порядок в наборе

2023-01-04 06:19 UTC, moodpulse requested changes

2023-01-04 06:19 UTC, moodpulse commented on api/views.py
> +    if len(SetResearch.objects.filter(pk=request_data["set"])) == 0:
Почему не .exists? Тут и ниже

2023-01-04 06:19 UTC, moodpulse commented on api/views.py
> +    if result["ok"]:
Тут можно сильно лучше сделать, что бы не писать такого странного условия) 
Сделать return в местах, где ошибка и возвращать status_response (у нас такая функция в л2 есть, которая возвращает OK и message) 
Собирать руками result нет необходимости

2023-01-04 06:19 UTC, moodpulse commented on api/views.py
> +def update_order(request):
Тут такие же моменты, как и выше

2023-01-04 06:19 UTC, moodpulse commented on contracts/models.py
> +        return False
Почему False? Тут по логике должно быть None.
И вообще условие излишне. 
Достаточно просто сделать return ...objects.filter(...).first()

2023-01-04 06:19 UTC, moodpulse commented on contracts/models.py
> +    def get_company_price_by_date(company_id, date_start, date_end):
К тому же функция называется и принимает в себя даты, но применения не вижу этих дат

2023-01-04 06:19 UTC, moodpulse commented on contracts/models.py
> +        return {i.research.pk: i.coast for i in PriceCoast.objects.filter(price_name=price, research_id__in=researches)}
research_id будет эффективнее research pk, потому что в случае с pk происходит выборка research для каждой записи

2023-01-04 06:19 UTC, moodpulse commented on l2-frontend/src/construct/ConstuctSetsResearch.vue
> +  margin: 1rem 0;
Отступ по rem несет в себе какой то особый смысл?)

2023-01-04 06:19 UTC, moodpulse commented on l2-frontend/src/mainWithRouter.ts
> +      path: '/ui/construct/sets-research',
На суть не влияет, но по английски вернее было бы research sets

2023-01-04 07:56 UTC, urchinpro commented on contracts/models.py
> +    def get_company_price_by_date(company_id, date_start, date_end):
поправлено

2023-01-04 07:56 UTC, urchinpro commented on contracts/models.py
> +        return {i.research.pk: i.coast for i in PriceCoast.objects.filter(price_name=price, research_id__in=researches)}
поправлено

2023-01-04 07:57 UTC, urchinpro commented on contracts/models.py
> +        return False
поправлено

2023-01-05 13:46 UTC, urchinpro approved these changes

2023-01-05 16:58 UTC, moodpulse requested changes

2023-01-05 16:58 UTC, moodpulse commented on statistic/views.py
> +            head_data = {i.research.pk: i.research.title for i in set_research}
Тут research pk стоит тоже поменять на research_id
Как и в других подобных местах

2023-01-06 10:02 UTC, merged