Research sets return
mikhailprivalov/l2 pull request #2432
Opened 2023-01-09 13:08 UTC by Wellheor1

## Описание изменений
Откат изменений

2023-01-11 02:35 UTC, moodpulse commented
А почему revert не сделать именно revert-ом?

2023-01-13 07:01 UTC, moodpulse requested changes
Один момент

2023-01-13 07:01 UTC, mikhailprivalov commented on api/views.py
> +    if current_set.hide:
Можно обойтись одним return, где будет просто взято это значение

2023-01-16 00:53 UTC, urchinpro approved these changes

2023-01-17 13:13 UTC, merged