Конструктор прайсов: создание и редактирование прайсов
mikhailprivalov/l2 pull request #2456
Opened 2023-01-17 07:44 UTC by Wellheor1

## Описание изменений
* Создание и редактирование прайсов (название, дата начала, дата конца, компания)
* fix названий, функций, стилей

2023-01-17 07:46 UTC, Wellheor1 commented
![image](https://user-images.githubusercontent.com/72241044/212838804-cbf394cb-ac6b-4bac-b4e0-1885ceab3be3.png)

2023-01-17 13:16 UTC, moodpulse requested changes

2023-01-17 13:16 UTC, moodpulse commented on api/views.py
> +        for data in PriceCoast.objects.filter(price_name_id=request_data).order_by('research__title')
Тут нужен prefetch related для research
Иначе у тебя будет N запросов за исследованиями, где N = количество прайсов

2023-01-17 21:12 UTC, moodpulse commented on api/views.py
> +        {"id": data.pk, "research": {"title": data.research.title, "id": data.research.pk}, "coast": data.coast.__str__()}
Почему data.coast.__str__()?
__ означает, что это приватное поле класса
нужно всегда в таких случаях пользоваться функцией str

2023-01-17 21:14 UTC, moodpulse commented on api/views.py
> +        {"id": data.pk, "research": {"title": data.research.title, "id": data.research.pk}, "coast": data.coast.__str__()}
А ещё правильнее было бы как то так f'{my_var:f}' или f'{my_var:.2f}'

2023-01-17 21:19 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      const coast = await this.$api('/get-coasts-researches-in-price', this.selectedPrice);
Странно напрямую прокидывать значение.
Лучше 
```suggestion
      const coast = await this.$api('/get-coasts-researches-in-price', {id: this.selectedPrice});
```

2023-01-19 12:57 UTC, urchinpro approved these changes

2023-01-19 13:56 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +      normalizer(node) {
Почему это не methods?

2023-01-19 17:02 UTC, moodpulse commented on l2-frontend/src/construct/ConstructPrice.vue
> +                :disabled="!priceIsActive"
А почему фронтовой валидации нет?

2023-01-20 11:53 UTC, merged