Fix contract culture title
mikhailprivalov/l2 pull request #2531
Opened 2023-02-19 10:23 UTC by urchinpro

## Описание изменений
Конструктор прайса - "лечение"
В контракте/маршрутизации/оезультаты - культуры

2023-02-19 11:02 UTC, moodpulse requested changes

2023-02-19 11:02 UTC, moodpulse commented on l2-frontend/src/pages/Statistics.vue
> +    // return (this.$store.getters.bases || []).filter(b => !b.hide);
Это не нужно думаю)

2023-02-19 11:02 UTC, moodpulse commented on l2-frontend/src/pages/Statistics.vue
> +      b.fin_sources.push({ pk: 0, title: 'Все', default_diagnos: '' });
Надо создавать новый массив в целом, а не мутировать
У тебя по ссылке поменяется значение во vuex

2023-02-19 20:55 UTC, moodpulse requested changes

2023-02-19 20:55 UTC, moodpulse commented on l2-frontend/src/pages/Statistics.vue
> +    const bsesUpdate = JSON.parse(JSON.stringify(this.$store.getters.bases));
Это не самый эффективный способ

2023-02-19 20:55 UTC, moodpulse commented on l2-frontend/src/pages/Statistics.vue
> +        b.fin_sources.push({ pk: 0, title: 'Все', default_diagnos: '' });
Pk 0 плохой вариант, потому что в теории возможно, что создание начнётся с нуля

2023-02-19 20:55 UTC, moodpulse commented on l2-frontend/src/pages/Statistics.vue
> +    const bsesUpdate = JSON.parse(JSON.stringify(this.$store.getters.bases));
Лучше скопировать через .map
И внутри сделать массив источников финансирования через спред оператор

2023-02-20 03:52 UTC, urchinpro commented on l2-frontend/src/pages/Statistics.vue
> +    const bsesUpdate = JSON.parse(JSON.stringify(this.$store.getters.bases));
ч/з map тоже state vuex изменяется

2023-02-20 03:58 UTC, urchinpro commented on l2-frontend/src/pages/Statistics.vue
> +    const bsesUpdate = JSON.parse(JSON.stringify(this.$store.getters.bases));
ч/з filter тоже

2023-02-20 13:00 UTC, merged