Restart_analyzer
mikhailprivalov/l2 pull request #2545
Opened 2023-02-27 01:47 UTC by WarfoIomey

## Описание изменений

api/admin.py - Добавил указание порта и название службы systemd, к которому принадлежит анализатор.
api/admin.py - Добавил раздел для выбора, какой пользователь может управлять анализатором

api/models.py - Добавил в таблицу анализаторов, номер порта анализатора и название службы
api/models.py - Создал таблицу в БД, где показано какой пользователь может управлять анализатором

api/views.py - Добавил функцию get_manage_analyzer для вывода всего списка анализатора на страницу профили пользователей
api/views.py - Добавил функцию restart_analyzer для перезапуска службы анализатора
api/views.py - Добавил функцию manage_profile_analyzer для вывода на страницу анализаторов, которые принадлежат только текущему пользователю.
api/views.py - Добавил функцию status_analyzer, которая выводит на страницу статус
api/views.py - Добавил функцию get_status_analyzer, которая получает id анализатора и получает статус анализатора из консоли linux

----------------------------------------------------------------------------

Все обязательные проверки (с пометкой required) должны быть без ошибок.

При падении проверок Lint лучше локально запустить `black` на файлах из pull request.

Например `black results/forms/forms107.py`

2023-03-01 02:20 UTC, urchinpro commented on api/models.py
> +    ports = models.PositiveSmallIntegerField(blank=True, null=True, help_text="Номер порта анализатора")
поменять название на port

2023-03-01 02:21 UTC, urchinpro commented on api/models.py
> +    doc_prof = models.ForeignKey(DoctorProfile, help_text="Пользователь, который принадлежит к этому анализатору", on_delete=models.CASCADE)
поменять название на user или doctor_profile

2023-03-01 02:22 UTC, urchinpro commented on api/models.py
> +class ManageDocProfileAnalyzer(models.Model):
поменять название на ManageDoctorProfileAnalyzer

2023-03-01 02:35 UTC, urchinpro commented on api/views.py
> +    name = [{"service": g.analyzer.service_name} for g in ManageDocProfileAnalyzer.objects.filter(analyzer_id=request_data["pk"]).order_by('analyzer')]
ManageDocProfileAnalyzer.objects.filter(analyzer_id=request_data["pk"], doctor_profile= request.user.docprofile.pk).first()

2023-03-01 02:37 UTC, urchinpro commented on api/views.py
> +    restart_service = subprocess.Popen(["systemctl", "--user", "restart", name[0]["service"]])
name[0]["service"] => name.analyzer.service_name

2023-03-01 02:38 UTC, urchinpro commented on api/views.py
> +    current_user = request.user
request.user.doctorprofile

2023-03-02 06:08 UTC, urchinpro approved these changes

2023-03-02 11:15 UTC, moodpulse commented on api/models.py
> +        return str(self.doctor_profile)
Тогда уж как то так)
```suggestion
        return f"{self.doctor_profile} — {self.analyzer}"
```

2023-03-02 11:15 UTC, moodpulse commented on api/urls.py
> +    path('restart-analyze', views.restart_analyzer),
```suggestion
    path('restart-analyzer', views.restart_analyzer),
```

2023-03-02 11:15 UTC, moodpulse commented on api/urls.py
> +    path('manage-analyze', views.get_manage_analyzer),
```suggestion
    path('manage-analyzer', views.get_manage_analyzer),
```

2023-03-02 11:16 UTC, moodpulse commented on api/views.py
> +                analizator = Analyzer.objects.get(pk=g)
Где то Analyzer, а тут analizator
лучше в одном виде всё

2023-03-02 11:18 UTC, moodpulse commented on api/views.py
> +def get_manage_analyzer(request):
Не стоит писать прям в api/views.py
Лучше создать новую директорию в api

2023-03-02 11:19 UTC, mikhailprivalov commented on api/views.py
> +    name = ManageDoctorProfileAnalyzer.objects.filter(analyzer_id=request_data["pk"], doctor_profile_id=request.user.doctorprofile.pk).first()
Предлагаю во всех местах если пользователь админ, то разрешить рестартить любой

2023-03-02 11:20 UTC, moodpulse commented on context_processors/utils.py
> +                    "url": "/ui/manageAnalyze",
```suggestion
                    "url": "/ui/manage-analyzers",
```

2023-03-02 11:21 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +import * as actions from '../../../store/action-types';
```suggestion
import * as actions from '@/store/action-types';
```

2023-03-02 11:22 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +  button {
Отступы бы поправить

2023-03-02 11:23 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +          Cтатус
Скорее как то так
```suggestion
          Обновить статус
```
Или иконку добавить

2023-03-02 11:23 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +          :value="data"
Почему value?

2023-03-02 11:24 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +          :value="data"
И выше

2023-03-02 11:24 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +          v-tippy
Зачем это тут и выше?

2023-03-02 11:25 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/index.vue
> +        class="name table"
Что это за классы и зачем тут i тогда?
Если нужна иконка, то надо брать из fa

2023-03-02 11:26 UTC, mikhailprivalov commented on l2-frontend/src/pages/ManageAnalyzers/index.vue
> +        <col width="80">
Одну из колонок надо оставить без ширины
Таблица я не уверен что вся 505 пикселей
И что бы ширина нормально работала — таблице нужен класс table-fixed

2023-03-02 11:26 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/index.vue
> +            Нет Анализаторов
```suggestion
            Нет анализаторов
```

2023-03-02 11:26 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/index.vue
> +          :value="row.pk"
Зачем тут value?

2023-03-02 11:27 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/index.vue
> +    async getProfileAnalyzer() {
тут надо добавить индикацию загрузки

2023-03-02 11:28 UTC, moodpulse commented on l2-frontend/src/pages/Profiles.vue
> +    async getAnalyzer() {
Нейминг непонятный, видимо надо getAllAnalyzers
И нет индикации загрузки

2023-03-02 11:28 UTC, moodpulse commented on l2-frontend/src/pages/Profiles.vue
> +      const list = await this.$api('manage-analyze');
Вообще этот урл в целом непонятный
Выше я про него писал, но в целом он должен отражать суть
Что то вроде
```suggestion
      const list = await this.$api('manage-analyzers/all-analyzers');
```

2023-03-02 11:28 UTC, moodpulse commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Это надо удалить

2023-03-02 11:31 UTC, moodpulse commented on api/views.py
> +                  "pk": analyzerList.id} for analyzerList in Analyzer.objects.all().order_by('title', 'id')]
Нейминг в формате camelCase не надо в питоне использовать. Плюс тут на каждой итерации не список, а отдельные анализаторы, так что:
```suggestion
                  "pk": analyzer.id} for analyzer in Analyzer.objects.all().order_by('title', 'id')]
```

И нехватает фильтрации, что бы убрать анализаторы с пустыми портами и service name

2023-03-02 11:32 UTC, moodpulse commented on api/views.py
> +    lsof_command = f'lsof -i :{port}'.split()
Действительно ли надо сначала формировать строку, а потом сплит? Почему бы сразу список не сделать?

2023-03-02 11:33 UTC, moodpulse commented on api/views.py
> +def get_status_analyzer(arg):
Тут мы проверяем, что порт есть
Но неплохо бы ещё проверить статус службы

2023-03-02 11:33 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +          {{ g }}
Вижу, что в g есть id — значит это объект, а тут он прям как есть используется

2023-03-02 11:34 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +          {{ g }}
Но в g как будто бы id нет
Это вроде строка
И надо назвать ее нормально, а не абстрактно **g**

2023-03-02 11:35 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +    async restartAnalyze(data) {
```suggestion
    async restartAnalyzer(data) {
```

2023-03-02 11:35 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +    async restartAnalyze(data) {
И тут аргумент вообще излишний
pk можно получить из пропсов

2023-03-02 11:35 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +    async getStatus(data) {
Тут тоже аргумент не нужен

2023-03-02 11:36 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +        pk: data.pk,
this.$api умеет забирать ключ более удобно
С учетом правок, что аргумент не нужен — будет так
```typescript
        const list = await this.$api('restart-analyzer', this.data, 'pk');
```

2023-03-02 18:14 UTC, moodpulse requested changes
Есть вопросы, которые надо решить

2023-03-03 02:31 UTC, urchinpro commented on api/views.py
> +    lsof_command = f'lsof -i :{port}'.split()
['lsof', '-i', f':{port}']

2023-03-17 05:54 UTC, moodpulse requested changes

2023-03-17 05:54 UTC, moodpulse commented on api/analyzers/views.py
> +        name = ManageDoctorProfileAnalyzer.objects.filter(analyzer_id=request_data["pk"], doctor_profile_id=request.user.doctorprofile.pk).first()
От админа это не сработает
Для админа системы не надо создавать кучу manage doctor profile
Он должен мочь смотреть и рестартить любой

2023-03-17 05:57 UTC, moodpulse requested changes

2023-03-17 05:57 UTC, moodpulse commented on l2-frontend/src/mainWithRouter.ts
> +      path: '/ui/all_analyzers',
Нижних подчёркиваний в URL не надо.

2023-03-17 05:57 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/components/Row.vue
> +        id="template-systemctl"
Это должен быть динамический id.
На странице id должен быть уникальный. А тут их куча одинаковых

2023-03-17 12:22 UTC, moodpulse requested changes

2023-03-17 12:22 UTC, mikhailprivalov commented on api/analyzers/views.py
> +    if su:
Надо устранить дублирование кода
Ведь можно получить name и положить в переменную
А код рестарта будет тот же

2023-03-17 12:22 UTC, mikhailprivalov commented on api/analyzers/views.py
> +        return JsonResponse({"data": filter_analyzer})
Тут тоже чуть меньше дублирования можно
```suggestion
    return JsonResponse({"data": filter_analyzer})
```

А верхний return убрать

2023-03-17 12:22 UTC, mikhailprivalov commented on api/analyzers/views.py
> +        filter_analyzer = [{"label": g.title, "pk": g.pk} for g in Analyzer.objects.all().order_by('title', 'pk')]
Тут и ниже нехватает фильтрации по service name
Нам не нужны "мусорные" анализаторы

2023-03-17 12:22 UTC, moodpulse commented on l2-frontend/src/pages/ManageAnalyzers/index.vue
> +<style lang="scss" scoped>
Это можно убрать

2023-03-21 08:15 UTC, mikhailprivalov requested changes

2023-03-21 08:15 UTC, moodpulse commented on api/analyzers/views.py
> +def restart_analyzer(request):
Не вижу тут контроля доступа

2023-03-21 08:15 UTC, moodpulse commented on api/views.py
> +from api.models import ManageDoctorProfileAnalyzer
Одной строчкой лучше всё импортировать

2023-03-29 01:47 UTC, merged