Manage_chamber
mikhailprivalov/l2 pull request #2677
Opened 2023-04-12 04:10 UTC by WarfoIomey

## Описание изменений

1) Добавлена страница "Управление палатами"
2) Возможность получить список не распределенных пациентов по подразделению
3) Возможность получить список пациентов, которые находятся в ожидании на кровать
4) Возможность получить список врачей, по подразделению
5) Возможность переносить из списка пациентов на кровать (только, если она пустая) или в список ожидания
6) Возможность переносить из списка врачей на иконку Б/В (только, если есть пациент на кровати)
7) Возможность кликнуть на врача из списка и подсветятся имя на кроватях, к которым прикреплен (повторное нажатие скроет)
8) Возможность переносить врача из иконки врача обратно список врачей или врач автоматически уберётся если убрать пациента
9) Возможность переносить пациента из кровати в список ожиданий или в список пациентов
10) Пол пациентов отображается в цвете иконки человека или иконки кровати (Розовый: девочка, Голубой: мальчик)
11) Слева от иконки врача отображается возраст пациента
12) Справа от иконки сверху отображается сокращенное ФИО пациента, снизу сокращенное ФИО врача
13) Ведётся подсчет общее количество кроватей по всем палатам, а так-же количество занятых, и сколько из них девочек и мальчиков
14) Ведётся подсчёт количество пациентов, которые находятся в распоряжении у врача (в списке врачей, справа от ФИО)

----------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/97881512/231346776-9596dcc7-95c3-4ed3-a8d5-f78c9fa7b51d.png)
![image](https://user-images.githubusercontent.com/97881512/231346818-2a80037b-01dd-49d9-85b2-51f320fe314e.png)
![image](https://user-images.githubusercontent.com/97881512/231346882-dd6f4ad4-1eaa-4e0d-8d5b-eb2f56461aef.png)
![image](https://user-images.githubusercontent.com/97881512/231346933-544ac2c2-2296-498f-9fb4-91a42f154bbc.png)
![image](https://user-images.githubusercontent.com/97881512/231346987-1a113e60-4d02-40b2-9b92-b5369a45cea5.png)

Все обязательные проверки (с пометкой required) должны быть без ошибок.

При падении проверок Lint лучше локально запустить `black` на файлах из pull request.

Например `black results/forms/forms107.py`

2023-05-15 03:47 UTC, WarfoIomey commented
Как лучше сделать 
Version 1 
index
` <Filters`
         `     :filters="filters"`
         `     :departments="departments"`
   `/>`
` <Filters`
         `     :filters="filtersDoc"`
         `     :departments="departments"`
`/>`
`const filters = ref({`
  `department_pk: -1,`
`});`
`const filtersDoc = ref({`
  `department_pk: -1,`
`});`
`const department = computed(() => filters.value.department_pk);`
`const departmentDoc = computed(() => filtersDoc.value.department_pk);`

filters
`<Treeselect`
     `     v-model="/* eslint-disable-line vue/no-mutating-props */ filters.department_pk"`
     `     :multiple="false"`
     `    :disable-branch-nodes="true"`
     `    :options="departments"`
     `    placeholder="Отделение не выбрано"`
     `     :append-to-body="true"`
`/>`
` props: {`
    `filters: {
      type: Object,
      required: true,
    },`
    `departments: {
      type: Array,
      required: true,
    },`
  },`

Version 2

index
`<Filters`
         `      :departments="departments"`
         `     @input="getDepartPatientId($event)"`
`/>`
`<Filters`
         `      :departments="departments"`
         `      @input="getDepartDocId($event)"`
`/>`
`const departmentPatientPk = ref(-1);`
`const departmentDocPk = ref(-1);`
`function getDepartDocId(data) {`
  `     departmentDocPk.value = data;`
`}`
`function getDepartPatientId(data) {`
  `     departmentPatientPk.value = data;`
`}`
filters
` <Treeselect` 
   `       v-model="/* eslint-disable-line vue/no-mutating-props */ departId"` 
    `      :multiple="false"` 
   `       :disable-branch-nodes="true"` 
   `       :options="departments"` 
   `       placeholder="Отделение не выбрано"` 
   `       :append-to-body="true"` 
    `      @input="$emit('input', departId)"` 
 ` />`
`const props = defineProps(['departments']);`
`const departId = ref(-1);`
Или как то по другому?

2023-05-16 12:49 UTC, moodpulse requested changes

2023-05-16 12:49 UTC, moodpulse commented on podrazdeleniya/models.py
> +class Chamber(models.Model):
В моделях не вижу ни одного индекса
Нужно на основании запросов их сюда добавить (во все модели, какие индексы необходимы)

2023-05-16 12:49 UTC, moodpulse commented on context_processors/utils.py
> +                    "access": ["Палаты"]
Раз тут указана группа, то почему по этой группе не ограничены api?

2023-05-16 12:49 UTC, moodpulse commented on api/chambers/views.py
> +    if department_pk != -1:
Зачем тогда вообще давать делать запрос, если передается -1?

2023-05-16 12:49 UTC, moodpulse commented on api/chambers/views.py
> +        individual_obj = Individual.objects.get(family=patient_data["family"])
Я не понимаю, что тут происходит
Почему мы ищем физ лицо по фамилии?
Оно ведь кроме того упадет, если существует несколько физ лиц с одной фамилией

2023-05-16 12:49 UTC, moodpulse commented on api/chambers/views.py
> +        for j in Bed.objects.filter(chamber_id=i.pk):
почему переменные называются i и j?
Нужно дать нормальные названия, не стоит экономить символы)

2023-05-16 12:49 UTC, mikhailprivalov commented on api/chambers/views.py
> +        for j in Bed.objects.filter(chamber_id=i.pk):
Кроме этого Bed лучше выбрать через prefetch_related, что бы не делать N запросов

2023-05-16 12:49 UTC, moodpulse commented on api/chambers/views.py
> +            "short_fio": f'{patient.family} {patient.name[0]}. {patient.patronymic[0]}.',
Отчества может и не быть

2023-05-16 12:49 UTC, moodpulse commented on api/chambers/views.py
> +            "age": today.year - patient.birthday.year,
А точно нужен именно такой вариант возраста без учёта даты?

2023-05-16 12:49 UTC, mikhailprivalov commented on l2-frontend/src/pages/ManageChambers/components/Filters.vue
> +    v-model="/* eslint-disable-line vue/no-mutating-props */ departId"
Это не нужно eslint-disable-line vue/no-mutating-props
А если нужно, то код некорректный

2023-05-16 12:49 UTC, moodpulse commented on l2-frontend/src/pages/ManageChambers/index.vue
> +function getDepartDocId(data) {
Почему get, а не set?
и ниже
И к тому же эти функции лучше переместить ниже, они тут намешаны с определениями значений

2023-05-16 12:49 UTC, mikhailprivalov commented on l2-frontend/src/pages/ManageChambers/index.vue
> +async function changeDoctor({ added, removed }, bed) {
Добавь хот отступов между функциями
Читать очень тяжело
И непонятно, почему function, а не стрелочные функции

2023-05-16 12:49 UTC, mikhailprivalov commented on l2-frontend/src/pages/ManageChambers/index.vue
> +  bed.doctor.pop();
Лучше объекты не мутировать, а создавать новые

2023-05-19 03:25 UTC, WarfoIomey commented on l2-frontend/src/pages/ManageChambers/index.vue
> +  bed.doctor.pop();
Не уверен, что это правильно
`const clearArrayDoctor = (bed) => {`
  `// eslint-disable-next-line no-param-reassign`
 ` bed.doctor = bed.doctor.filter(doctor => !bed.doctor.includes(doctor));`
`};`

2023-05-19 03:25 UTC, WarfoIomey commented on l2-frontend/src/pages/ManageChambers/index.vue
> +async function changeDoctor({ added, removed }, bed) {
Исправил

2023-05-19 03:26 UTC, WarfoIomey commented on l2-frontend/src/pages/ManageChambers/index.vue
> +function getDepartDocId(data) {
Исправил

2023-05-19 03:26 UTC, WarfoIomey commented on l2-frontend/src/pages/ManageChambers/components/Filters.vue
> +    v-model="/* eslint-disable-line vue/no-mutating-props */ departId"
Исправил, работает без eslint-disable-line vue/no-mutating-props

2023-05-19 03:27 UTC, WarfoIomey commented on api/chambers/views.py
> +            "age": today.year - patient.birthday.year,
В sql функций прописал подсчет возраста с учетом (год, месяца, дня)

2023-05-19 03:27 UTC, WarfoIomey commented on api/chambers/views.py
> +        for j in Bed.objects.filter(chamber_id=i.pk):
Исправил

2023-05-19 03:28 UTC, WarfoIomey commented on api/chambers/views.py
> +        individual_obj = Individual.objects.get(family=patient_data["family"])
Исправил

2023-05-19 03:28 UTC, WarfoIomey commented on api/chambers/views.py
> +    if department_pk != -1:
Исправил

2023-05-19 03:30 UTC, WarfoIomey commented on context_processors/utils.py
> +                    "access": ["Палаты"]
Исправил

2023-05-19 03:30 UTC, WarfoIomey commented on podrazdeleniya/models.py
> +class Chamber(models.Model):
Исправил

2024-10-04 13:16 UTC, merged