Загрузка вредных факторов + мед. осмотры
mikhailprivalov/l2 pull request #2714
Opened 2023-04-18 05:52 UTC by Wellheor1

## Описание изменений
* fix-ы загрузки xlsx файла с вредными факторами
* Данные о мед. осмотрах компании за день/месяц

2023-04-19 23:14 UTC, moodpulse commented on contracts/models.py
> +    card = models.ForeignKey(Card, help_text="Карта пациента", on_delete=models.CASCADE)
А где индекс на карту?
Ниже по ней фильтрация для удаления

2023-04-19 23:16 UTC, moodpulse commented on contracts/models.py
> +        MedicalExamination.objects.filter(card=card).delete()
А почему надо делать именно так, а не к примеру модифицировать существующую запись?

2023-04-19 23:17 UTC, moodpulse commented on contracts/models.py
> +        MedicalExamination.objects.filter(card=card).delete()
Удаление не самая приятная процедура для базы

2023-04-19 23:18 UTC, moodpulse commented on api/parse_file/views.py
> +        current_fio = i + " " + fio.split(' ')[1] + " " + fio.split(' ')[2]
Два раза сплитим одно и то же
И очень надеемся, что точно будет элемент с индексом 2, хотя у нас вполне законно существовать без отчества

2023-04-19 23:19 UTC, moodpulse commented on api/parse_file/views.py
> +    patient_card = ''
Почему строка?
Никогда не надо использовать как пустое значение строку.
Для этого существует None

2023-04-19 23:21 UTC, moodpulse commented on api/parse_file/views.py
> +        "bd": birthday.split(' ')[0].replace('-', ''),
Тут везде у тебя много одинаковых сплитов.
Это много лишней работы

2023-04-19 23:24 UTC, moodpulse commented on api/parse_file/views.py
> +            request_obj.META["HTTP_AUTHORIZATION"] = f'Bearer {Application.objects.first().key}'
Почему first?
А если оно отключено?
Для этого надо специальное приложение сделать со специальным флажком.
Лучше сразу универсальное, типа is_background_worker
И искать как active=True и is_background_worker=True

2023-04-19 23:28 UTC, moodpulse reviewed
Обратить внимание:
1. Отчество не является обязательным
2. Даты странно преобразовываются сплитами, интами итд. Для этого есть специальные функции.
3. Много магического и слабо понятного кода. Через месяц тут будет сложно разобраться.

2023-04-19 23:28 UTC, mikhailprivalov requested changes
Надо поработать над качеством.

2023-04-20 01:41 UTC, Wellheor1 commented on contracts/models.py
> +        MedicalExamination.objects.filter(card=card).delete()
На одного пациента может быть только один осмотр, если он изменил работу и т .д старое уже не нужно
+ @urchinpro сказал так)

2023-04-21 02:30 UTC, Wellheor1 commented on contracts/models.py
> +    card = models.ForeignKey(Card, help_text="Карта пациента", on_delete=models.CASCADE)
Поправил

2023-04-21 02:30 UTC, Wellheor1 commented on contracts/models.py
> +        MedicalExamination.objects.filter(card=card).delete()
Поправил

2023-04-21 02:30 UTC, Wellheor1 commented on api/parse_file/views.py
> +        current_fio = i + " " + fio.split(' ')[1] + " " + fio.split(' ')[2]
Поправил

2023-04-21 02:31 UTC, Wellheor1 commented on api/parse_file/views.py
> +    patient_card = ''
Поправил

2023-04-21 02:31 UTC, Wellheor1 commented on api/parse_file/views.py
> +        "bd": birthday.split(' ')[0].replace('-', ''),
Поправил

2023-04-21 02:31 UTC, Wellheor1 commented on api/parse_file/views.py
> +            request_obj.META["HTTP_AUTHORIZATION"] = f'Bearer {Application.objects.first().key}'
Поправил

2023-04-23 12:43 UTC, moodpulse requested changes

2023-04-23 12:43 UTC, moodpulse commented on contracts/models.py
> +            date_end = datetime.date(int(date.split('-')[0]), int(date.split('-')[1]), num_day)
Тут куча сплитов осталась
И работа с датами как с числами
Тут не нужен ни сплит ни преобразование в int ни что либо ещё такое

Надо просить дату и менять день

2023-04-23 12:49 UTC, moodpulse commented on contracts/models.py
> +            date_end = datetime.date(int(date.split('-')[0]), int(date.split('-')[1]), num_day)
Но самый минимум - убрать дублирование сплитов

2023-04-24 01:11 UTC, Wellheor1 commented on contracts/models.py
> +            date_end = datetime.date(int(date.split('-')[0]), int(date.split('-')[1]), num_day)
Поправил

2023-04-24 01:17 UTC, Wellheor1 commented on contracts/models.py
> +            date_end = datetime.date(int(date.split('-')[0]), int(date.split('-')[1]), num_day)
Ещё есть что допилить - в черновик превратил

2023-04-26 00:02 UTC, Wellheor1 commented on contracts/models.py
> +            date_end = datetime.date(int(date.split('-')[0]), int(date.split('-')[1]), num_day)
@moodpulse  - вернул

2023-04-27 03:58 UTC, moodpulse commented on api/views.py
> +    return status_response(True)
Это точно нужно?)

2023-04-27 04:01 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +        selectedAllChange: ({ isSelected, selectedRowKeys }) => {
На эти подсказки нужно тоже обратить внимание

2023-04-27 04:01 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +  .btn {
С форматированием плохо)

2023-04-27 04:04 UTC, moodpulse commented on l2-frontend/src/construct/ConstructCompany.vue
> +        selectedAllChange: ({ isSelected, selectedRowKeys }) => {
(они видны, если открыть вкладку Files changed

2023-04-27 05:15 UTC, Wellheor1 commented on api/views.py
> +    return status_response(True)
Это с @urchinpro потом доделываться будет

2023-04-27 05:33 UTC, Wellheor1 commented on l2-frontend/src/construct/ConstructCompany.vue
> +        selectedAllChange: ({ isSelected, selectedRowKeys }) => {
Поправил

2023-04-27 05:33 UTC, Wellheor1 commented on l2-frontend/src/construct/ConstructCompany.vue
> +  .btn {
Поправил

2023-04-30 05:50 UTC, merged