Medical certificate
mikhailprivalov/l2 pull request #761
Opened 2020-09-10 03:33 UTC by urchinpro

2020-09-10 14:44 UTC, moodpulse commented on l2-frontend/src/ui-cards/MedicalCertificates.vue
> +    /*line-height: 1.1;*/
Коммент

2020-09-10 14:44 UTC, moodpulse commented on l2-frontend/src/ui-cards/MedicalCertificates.vue
> +        console.log(type_form, direction)
Лог убрать стоит

2020-09-10 20:58 UTC, moodpulse requested changes
Стоит убрать лог

2020-09-11 00:38 UTC, moodpulse commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +              <medical-certificates :med_certificates="data.medical_certificates" :direction="data.direction.pk"/>
Как насчёт сделать их отключение? По setting manager

2020-09-11 08:17 UTC, urchinpro commented on l2-frontend/src/pages/ResultsParaclinic.vue
> +              <medical-certificates :med_certificates="data.medical_certificates" :direction="data.direction.pk"/>
в цель? Они создаются ч/з dj-админку! Если справок нет, то слово "Справки не отображается"

2020-09-11 10:11 UTC, moodpulse approved these changes

2020-09-12 10:05 UTC, merged