место работы и должность: автоподстановка в ссылочное поле
mikhailprivalov/l2 pull request #764
Opened 2020-09-17 07:09 UTC by urchinpro

2020-09-19 21:53 UTC, moodpulse requested changes

2020-09-19 21:53 UTC, moodpulse commented on directions/models.py
> +    workplace = models.CharField(max_length=255, blank=True, default='', db_index=True)
Зачем в направлениях этот db_index?

2020-09-20 00:14 UTC, urchinpro commented on directions/models.py
> +    workplace = models.CharField(max_length=255, blank=True, default='', db_index=True)
отчеты понему делаться будут большие

2020-09-20 00:51 UTC, moodpulse approved these changes

2020-09-20 00:55 UTC, merged