Form30 plan
mikhailprivalov/l2 pull request #779
Opened 2020-10-04 11:45 UTC by urchinpro

2020-10-04 14:59 UTC, moodpulse commented on forms/forms100.py
> +    year = '2020'
Не надо жестко зашивать

2020-10-04 15:00 UTC, moodpulse commented on forms/forms100.py
> +    year = '2020'
Не сложнее сделать забор из query со значением по умолчанию 2020, что то вроде
year = request_data.get('year', '2020')

2020-10-04 15:01 UTC, moodpulse commented on forms/forms100.py
> +                dates_plan = f"{dates_plan} {normalize_date(date)[0:5]};"
Зачем делать слайс?
И приводить дату к строке?
Почему не сделать тут так?
```suggestion
                dates_plan = f"{dates_plan} {p.date.year};"
```

2020-10-04 15:01 UTC, moodpulse commented on forms/forms100.py
> +                dates_plan = f"{dates_plan}{normalize_date(date)[0:5]};"
Тут тот же вопрос

2020-10-04 15:02 UTC, moodpulse commented on l2-frontend/src/pages/ResultsDepartment.vue
> +                     @click="print()">
```suggestion
                     @click="print">
```

2020-10-04 15:03 UTC, moodpulse commented on l2-frontend/src/pages/ResultsDepartment.vue
> +      async print(type) {
```suggestion
      async print() {
```

2020-10-04 15:03 UTC, moodpulse commented on l2-frontend/src/pages/ResultsDepartment.vue
> +        const {results} = await directions_point.getDirectionsTypeDate({
```suggestion
        const {results} = await directions_point.getDirectionsTypeDate(this, ['is_lab', 'is_paraclinic', 'is_doc_refferal', 'date']);
```

2020-10-04 15:04 UTC, moodpulse commented on l2-frontend/src/pages/ResultsDepartment.vue
> +        const {results} = await directions_point.getDirectionsTypeDate({
Не надо руками доставать поля, если не требуется менять названия или ещё что то

2020-10-04 15:04 UTC, moodpulse commented on l2-frontend/src/pages/ResultsDepartment.vue
> +        const {results} = await directions_point.getDirectionsTypeDate({
Специально же сделана абстракция

2020-10-04 15:05 UTC, moodpulse commented on l2-frontend/src/pages/ResultsDepartment.vue
> +        this.print_results(results);
```suggestion
        this.$root.$emit('print:results', results)
```

2020-10-04 15:05 UTC, moodpulse commented on l2-frontend/src/pages/ResultsDepartment.vue
> +      print_results(pk) {
Эта функция не нужна

2020-10-04 15:08 UTC, moodpulse requested changes
Несколько вопросов

2020-10-04 19:18 UTC, moodpulse commented on forms/forms100.py
> +    year = '2020'
Ещё лучше по умолчанию текущий год

2020-10-05 00:27 UTC, urchinpro commented on forms/forms100.py
> +                dates_plan = f"{dates_plan} {normalize_date(date)[0:5]};"
здесь берется не год. Т.к . на каждый год карта своя то нужно число месяц в формате 01.03. Если 
p.date.month p.date.day - то отдается 2 и 9 без нулей - придется добавлять нули спереди.  normalize_date - быстрее это сделать

2020-10-05 00:27 UTC, urchinpro commented on forms/forms100.py
> +                dates_plan = f"{dates_plan}{normalize_date(date)[0:5]};"
нужен день месяц а не год - выше расписано

2020-10-05 00:27 UTC, urchinpro commented on forms/forms100.py
> +    year = '2020'
сделал

2020-10-05 07:47 UTC, moodpulse commented on forms/forms100.py
> +                dates_plan = f"{dates_plan} {normalize_date(date)[0:5]};"
Тут совсем не понятно, что происходит
Лучше сделать понятнее, что такое этот [0:5] – можно понять, только всё досконально изучив
Почему не сделать сразу тогда нужную строку, не "нормализовать дату"
У нас есть утилита – strfdatetime можно передать шаблон, какую дату надо получить, например
```suggestion
                dates_plan = f"{dates_plan} {strfdatetime(p.date, '%d.%m')};"
```

2020-10-05 07:50 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Вообще у нас же есть почти такой же участок кода.
Вопрос: почему не обобщить?

2020-10-05 07:50 UTC, moodpulse requested changes
Пара вопросов

2020-10-05 07:55 UTC, moodpulse commented on api/directions/views.py
> +def directions_type_date(request):
Сразу после релиза.думаю стоит все эти утилиты вынести в отдельный файл

2020-10-05 07:55 UTC, moodpulse commented on api/directions/views.py
> +def directions_type_date(request):
А то тут уже свалка из всего подряд

2020-10-05 07:56 UTC, moodpulse commented on api/directions/views.py
> +def directions_type_date(request):
То есть провести чистку кода в новой ветке, можно там же рефакторинг – объединить те два цикла перебора дисп плана, которые по своей сути одинаковые

2020-10-05 07:58 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Расписал в другом месте, когда это стоит сделать https://github.com/moodpulse/l2/pull/779#discussion_r499406022

2020-10-05 07:59 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Отдельной веткой можно

2020-10-05 08:00 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Потом

2020-10-05 08:01 UTC, urchinpro commented on forms/forms100.py
> +    for i in research_need:
ну сейчас нету времени, чтобы обобщать!
Обобщаться будет так как еще не доделаны чтоб выводился план визитов и факта
<img width="723" alt="Снимок экрана 2020-10-05 в 16 00 34" src="https://user-images.githubusercontent.com/41939763/95054182-10fa7a80-0724-11eb-8353-b964ff68f135.png">

2020-10-05 08:03 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
В любом случае стоило сразу делать отдельно, что было бы не сложнее

2020-10-05 08:03 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
А сейчас двойная работа

2020-10-05 08:03 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Поэтому в ближайшем будущем стоит провести чистку кода

2020-10-05 08:04 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Не вижу тут больших проблем

2020-10-05 08:05 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Так же стоит по диспансеризации ещё утилиты, которые в load_dreg используются – вынести в отдельный файл, а то рядом со view лежат какие то функции

2020-10-05 08:05 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Это дел на 5 часов

2020-10-05 08:05 UTC, moodpulse commented on forms/forms100.py
> +    for i in research_need:
Может на 3

2020-10-05 08:20 UTC, moodpulse approved these changes

2020-10-05 11:40 UTC, merged